### ISSUE TITLE
sndhdr testsuite missing sndhdrdata directory

### ISSUE THREAD

**Issue by lucas42** [youknowone/python-deadlib#20]
The sndhdr tests depend on a directory named sndhdrdata, which isn't available here.

```
EE
======================================================================
ERROR: test_data (tests.test_sndhdr.TestFormats.test_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sndhdr/tests/test_sndhdr.py", line 22, in test_data
    what = sndhdr.what(filename)
  File "/sndhdr/sndhdr/__init__.py", line 59, in what
    res = whathdr(filename)
  File "/sndhdr/sndhdr/__init__.py", line 65, in whathdr
    with open(filename, 'rb') as f:
         ~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sndhdrdata/sndhdr.8svx'

======================================================================
ERROR: test_pickleable (tests.test_sndhdr.TestFormats.test_pickleable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sndhdr/tests/test_sndhdr.py", line 33, in test_pickleable
    what = sndhdr.what(filename)
  File "/sndhdr/sndhdr/__init__.py", line 59, in what
    res = whathdr(filename)
  File "/sndhdr/sndhdr/__init__.py", line 65, in whathdr
    with open(filename, 'rb') as f:
         ~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sndhdrdata/sndhdr.aifc'

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
```

**Comment by lucas42** [comment]
This appears to be the directory in question: https://github.com/python/cpython/tree/3.12/Lib/test/sndhdrdata
